### ISSUE TITLE
Error if code name contains a '

### ISSUE THREAD

**Issue by potherca** [jakesankey/git-tab-status#9]
When I open a file that contains a `'` character error dialogs keep appearing until the file is closed again.
This can easily be reproduced by creating a file with a `'` in the title and then opening it in atom.

[Enter steps to reproduce below:]

1. Open a file that contains a `'` (for instance `foo'bar`)
2. Watch a load of error dialogs appear on your screen

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.3
**Thrown From**: [git-tab-status](https://github.com/jakesankey/git-tab-status) package, v1.7.0

### Stack Trace

Uncaught Error: Syntax error, unrecognized expression: .tab [data-path='/Users/ben/Dropbox/www/playground/Sandurz/sigterm.example (ben's conflicted copy 2015-03-12).sh']

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:1453

Error: Syntax error, unrecognized expression: .tab [data-path='/Users/ben/Dropbox/www/playground/Sandurz/sigterm.example (ben's conflicted copy 2015-03-12).sh']
    at Function.Sizzle.error (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:1453:8)
    at Sizzle.tokenize (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:2070:11)
    at Sizzle.select (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:2474:20)
    at Function.Sizzle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:850:9)
    at jQuery.fn.extend.find (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:2690:11)
    at jQuery.fn.init (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:2798:38)
    at jQuery (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:76:10)
    at GitTabStatus._findTabForPath (/Users/ben/.atom/packages/git-tab-status/lib/git-tab-status.coffee:76:14)
    at GitTabStatus._updateTabStylesForPath (/Users/ben/.atom/packages/git-tab-status/lib/git-tab-status.coffee:57:20)
    at GitTabStatus._updateTabStylesForPath (/Users/ben/.atom/packages/git-tab-status/lib/git-tab-status.coffee:3:61)
```

### Commands

```
     -1:00.6 application:open (atom-text-editor.editor)
     -0:22.7 core:select-down (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-light-syntax"
    ],
    "projectHome": "/Users/ben/dev",
    "disabledPackages": [
      "atom-html-preview",
      "autocomplete-phpunit",
      "phpunit"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autocomplete-css, v0.6.0
autocomplete-plus, v2.9.0
file-icons, v1.5.4
git-log, v0.3.0
git-tab-status, v1.7.0
minimap, v4.7.6
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-selection, v4.2.0

# Dev
No dev packages
```

**Comment by jakesankey** [comment]
This issue was resolved in version 1.8.0.
